### ISSUE TITLE
.... in particular, numpy and scipy require libatlas, libblas and liblapack

### ISSUE THREAD

**Issue by kootenpv** [antocuni/pypy-wheels#11]
What is the suggested way to `apt-get` them, e.g. in docker?

**Comment by mattip** [comment]
`apt install gfortran-5 libatlas-dev libatlas-base-dev libopenblas-dev liblapack-dev` should get you started

**Comment by antocuni** [comment]
after merging #6 ` libatlas-dev libatlas-base-dev liblapack-dev` are not longer needed. You should need only `libopenblas`. Please re-open the issue if it is not enough
