### ISSUE TITLE
use manylinux2010 as a base image

### ISSUE THREAD

**Issue by mattip** [antocuni/pypy-wheels#18]
manylinux2010 has been released. It requires pip>=19.0 but I think pypy users are sophisticated enough to do
`pypy -mpip install --upgrade pip setuptools` before `pip install`ing these wheels. What do you think?

**Comment by antocuni** [comment]
Ideally, I think that eventually pypy should ship a version of pip which is compatible with manylinux2010 by default, but I suppose it's too late now :)

Yes, I suppose that we could compile wheels *both* for ubuntu (using the current image) and manylinux2010: if you look at `docker/build_image.sh` you see that my scripts were already designed with the idea of building using multiple base images

**Comment by mattip** [comment]
> pypy should ship a version of pip which is compatible with manylinux2010 by default

Done for the next release

**Comment by Julian** [comment]
This is done now right?

**Comment by mattip** [comment]
Yes, closing
