### ISSUE TITLE
GitHub Pages deployment provider

### ISSUE THREAD

**Issue by webknjaz** [antocuni/pypy-wheels#8]
Hi,

I noticed that your Travis CI build is failing to push updates to `gh-pages` and you wrote a custom script to do this. I actually wrote a deployment provider for this purpose a while back. If you wish to use it, docs are here: https://docs.travis-ci.com/user/deployment/pages/.
And you can ask me if you need some assistance.

Ref: https://travis-ci.org/antocuni/pypy-wheels/jobs/371180724#L743
Src: https://github.com/travis-ci/dpl/blob/610be4a/lib/dpl/provider/pages.rb

**Comment by antocuni** [comment]
thanks for the link, but I think I'll keep using the current logic: I need it anyway to e.g. know which wheels are already built
